package com.tomaspinho.atvr.ui.theme

import androidx.compose.ui.graphics.Color

// Light scheme
val md_light_primary = Color(0xFFB45A00)
val md_light_onPrimary = Color(0xFFFFFFFF)
val md_light_primaryContainer = Color(0xFFFFDCC6)
val md_light_onPrimaryContainer = Color(0xFF3A1400)
val md_light_secondary = Color(0xFF755846)
val md_light_onSecondary = Color(0xFFFFFFFF)
val md_light_secondaryContainer = Color(0xFFFFDCC6)
val md_light_onSecondaryContainer = Color(0xFF2A1700)
val md_light_tertiary = Color(0xFF615B2C)
val md_light_onTertiary = Color(0xFFFFFFFF)
val md_light_tertiaryContainer = Color(0xFFE8E09F)
val md_light_onTertiaryContainer = Color(0xFF1D1900)
val md_light_error = Color(0xFFBA1A1A)
val md_light_onError = Color(0xFFFFFFFF)
val md_light_errorContainer = Color(0xFFFFDAD6)
val md_light_onErrorContainer = Color(0xFF410002)
val md_light_background = Color(0xFFFFF8F5)
val md_light_onBackground = Color(0xFF221A14)
val md_light_surface = Color(0xFFFFF8F5)
val md_light_onSurface = Color(0xFF221A14)
val md_light_surfaceVariant = Color(0xFFF3DED4)
val md_light_onSurfaceVariant = Color(0xFF51443A)
val md_light_outline = Color(0xFF837468)
val md_light_surfaceContainer = Color(0xFFF5EBE3)

// Dark scheme
val md_dark_primary = Color(0xFFFFB778)
val md_dark_onPrimary = Color(0xFF5B2700)
val md_dark_primaryContainer = Color(0xFF823F00)
val md_dark_onPrimaryContainer = Color(0xFFFFDCC6)
val md_dark_secondary = Color(0xFFE5B68E)
val md_dark_onSecondary = Color(0xFF442A18)
val md_dark_secondaryContainer = Color(0xFF5D402C)
val md_dark_onSecondaryContainer = Color(0xFFFFDCC6)
val md_dark_tertiary = Color(0xFFCCC486)
val md_dark_onTertiary = Color(0xFF332E00)
val md_dark_tertiaryContainer = Color(0xFF494516)
val md_dark_onTertiaryContainer = Color(0xFFE8E09F)
val md_dark_error = Color(0xFFFFB4AB)
val md_dark_onError = Color(0xFF690005)
val md_dark_errorContainer = Color(0xFF93000A)
val md_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_dark_background = Color(0xFF1A120C)
val md_dark_onBackground = Color(0xFFF0E6DD)
val md_dark_surface = Color(0xFF1A120C)
val md_dark_onSurface = Color(0xFFF0E6DD)
val md_dark_surfaceVariant = Color(0xFF51443A)
val md_dark_onSurfaceVariant = Color(0xFFD7C3B8)
val md_dark_outline = Color(0xFF9F8D81)
val md_dark_surfaceContainer = Color(0xFF251C16)

// True black (AMOLED) accent overrides
val amoled_background = Color(0xFF000000)
val amoled_surface = Color(0xFF000000)